/**
 * email.js — EmailJS integration for stock price & signal alerts
 * StockMonitor Pro v7
 *
 * EmailJS Credentials (update in Settings or directly here):
 *   Public Key  : fof2kfSPzOm-gRMrI
 *   Service ID  : service_yxemoqc
 *   Template ID : template_836mkd8
 *
 * EmailJS Template Variables expected:
 *   {{to_email}}      - recipient email
 *   {{from_name}}     - "StockMonitor Pro"
 *   {{subject}}       - alert subject line
 *   {{stock_symbol}}  - e.g. AAPL
 *   {{stock_name}}    - e.g. Apple Inc.
 *   {{alert_type}}    - e.g. "Price Alert", "RSI Alert"
 *   {{current_price}} - e.g. $182.30
 *   {{change_pct}}    - e.g. +1.24%
 *   {{signal}}        - BUY / SELL / HOLD / WATCH
 *   {{rsi_value}}     - e.g. 67.4
 *   {{message}}       - full alert message body
 *   {{timestamp}}     - date/time of alert
 */

// ── CONFIG (loaded from localStorage or defaults) ─────────────
function getEmailConfig() {
  return {
    publicKey:  localStorage.getItem('smp_ej_key')      || 'fof2kfSPzOm-gRMrI',
    serviceId:  localStorage.getItem('smp_ej_service')  || 'service_yxemoqc',
    templateId: localStorage.getItem('smp_ej_template') || 'template_836mkd8',
  };
}

// ── INIT EMAILJS ──────────────────────────────────────────────
function initEmailJS() {
  const cfg = getEmailConfig();
  if (typeof emailjs !== 'undefined' && cfg.publicKey) {
    emailjs.init({ publicKey: cfg.publicKey });
    console.log('[email] EmailJS initialized with key:', cfg.publicKey.slice(0, 8) + '...');
  } else {
    console.warn('[email] EmailJS not loaded or no public key configured.');
  }
}

// ── SEND ALERT EMAIL ──────────────────────────────────────────
async function sendAlertEmail(params) {
  const cfg = getEmailConfig();
  if (!cfg.publicKey || !cfg.serviceId || !cfg.templateId) {
    return { success: false, error: 'EmailJS not configured. Open Settings to add your keys.' };
  }

  const stock  = window.stockData[params.symbol] || {};
  const sigs   = (window.allSignals || {})[params.symbol] || {};
  const mag7   = MAG7.find(s => s.symbol === params.symbol) || {};
  const now    = new Date().toLocaleString('en-US', { timeZone: 'America/New_York', hour12: true });

  const templateParams = {
    to_email:      params.email || 'dsaisantoshkumar@gmail.com',
    from_name:     'StockMonitor Pro',
    subject:       `📊 ${params.alertType || 'Stock Alert'} — ${params.symbol} ${fmtPrice(stock.price)}`,
    stock_symbol:  params.symbol,
    stock_name:    mag7.name || params.symbol,
    alert_type:    params.alertType || 'Price Alert',
    current_price: fmtPrice(stock.price),
    change_pct:    stock.changePct != null ? fmtPct(stock.changePct) : '—',
    signal:        sigs.signal || '—',
    rsi_value:     sigs.rsi    != null ? sigs.rsi.toFixed(1) : '—',
    ma5:           sigs.ma5    != null ? '$' + sigs.ma5 : '—',
    ma20:          sigs.ma20   != null ? '$' + sigs.ma20 : '—',
    message:       params.message || buildDefaultMessage(params.symbol, stock, sigs),
    timestamp:     now + ' ET',
  };

  try {
    const response = await emailjs.send(cfg.serviceId, cfg.templateId, templateParams);
    console.log('[email] Alert sent!', response.status, response.text);
    return { success: true, response };
  } catch (err) {
    console.error('[email] Send failed:', err);
    return { success: false, error: err?.text || err?.message || 'Unknown error' };
  }
}

// ── BUILD DEFAULT MESSAGE BODY ────────────────────────────────
function buildDefaultMessage(symbol, stock, sigs) {
  return `
StockMonitor Pro — Alert Summary
════════════════════════════════
Symbol    : ${symbol}
Price     : ${fmtPrice(stock.price)}
Change    : ${stock.change != null ? fmtChange(stock.change) : '—'} (${stock.changePct != null ? fmtPct(stock.changePct) : '—'})
Day High  : ${fmtPrice(stock.high)}
Day Low   : ${fmtPrice(stock.low)}
Volume    : ${fmtVol(stock.volume)}

Technical Signals
─────────────────
Signal    : ${sigs.signal || '—'}
RSI (14)  : ${sigs.rsi   != null ? sigs.rsi.toFixed(1) : '—'}
MA5       : ${sigs.ma5   != null ? '$' + sigs.ma5 : '—'}
MA20      : ${sigs.ma20  != null ? '$' + sigs.ma20 : '—'}
MACD      : ${sigs.macd  != null ? sigs.macd : '—'}

Reasons   : ${(sigs.reasons || []).join(' · ') || '—'}

──────────────────────────────
Generated by StockMonitor Pro
${new Date().toLocaleString()}
  `.trim();
}

// ── SEND TEST ALERT (called from UI) ─────────────────────────
async function sendTestAlert() {
  const email  = document.getElementById('alertEmail')?.value;
  const symbol = document.getElementById('alertSymbol')?.value || 'AAPL';
  const type   = document.getElementById('alertType')?.value;
  const thresh = document.getElementById('alertThreshold')?.value;
  const status = document.getElementById('alertStatus');

  if (!email) { showAlertStatus('Please enter an email address.', 'error'); return; }

  showAlertStatus('⏳ Sending test alert...', 'sending');

  const result = await sendAlertEmail({
    email,
    symbol,
    alertType: `Test Alert — ${type}${thresh ? ' @ ' + thresh : ''}`,
    message:   `This is a test alert from StockMonitor Pro.\n\nAlert Config:\n  Symbol: ${symbol}\n  Type: ${type}\n  Threshold: ${thresh || 'N/A'}`,
  });

  if (result.success) {
    showAlertStatus(`✅ Test alert sent to ${email}! Check your inbox.`, 'success');
  } else {
    showAlertStatus(`❌ Failed: ${result.error}`, 'error');
  }
}

function showAlertStatus(msg, type) {
  const el = document.getElementById('alertStatus');
  if (!el) return;
  el.textContent = msg;
  el.className = 'alert-status ' + type;
}

// ── AUTO ALERT CHECKER (runs on refresh) ─────────────────────
async function checkAutoAlerts() {
  const alerts = JSON.parse(localStorage.getItem('smp_alerts') || '[]');
  if (!alerts.length) return;

  for (const alert of alerts) {
    const stock = window.stockData[alert.symbol];
    if (!stock) continue;

    let triggered = false;
    let reason = '';

    if (alert.type === 'above'  && stock.price >= alert.threshold)            { triggered = true; reason = `${alert.symbol} crossed above $${alert.threshold}`; }
    if (alert.type === 'below'  && stock.price <= alert.threshold)            { triggered = true; reason = `${alert.symbol} fell below $${alert.threshold}`; }
    if (alert.type === 'change' && Math.abs(stock.changePct) >= alert.threshold) { triggered = true; reason = `${alert.symbol} moved ${fmtPct(stock.changePct)}`; }

    const sigs = (window.allSignals || {})[alert.symbol] || {};
    if (alert.type === 'rsi_overbought' && sigs.rsi && sigs.rsi > 70) { triggered = true; reason = `${alert.symbol} RSI = ${sigs.rsi.toFixed(1)} (overbought)`; }
    if (alert.type === 'rsi_oversold'   && sigs.rsi && sigs.rsi < 30) { triggered = true; reason = `${alert.symbol} RSI = ${sigs.rsi.toFixed(1)} (oversold)`;   }

    if (triggered && !alert.sentToday) {
      console.log('[email] Auto-alert triggered:', reason);
      await sendAlertEmail({ email: alert.email, symbol: alert.symbol, alertType: reason });
      alert.sentToday = true;
    }
  }
  localStorage.setItem('smp_alerts', JSON.stringify(alerts));
}
